env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules: {
  "import/no-absolute-path": "off",
  "@typescript-eslint/no-non-null-assertion": "off",
  "@typescript-eslint/triple-slash-reference": "off",
  "@typescript-eslint/no-empty-interface": "off"
}
